 model_config: 
  model_name: mulbert
  pretrained_bert: bert-base-uncased
  mlm_loss_weight: 0.1
  audio_loss_weight: 4.0
  atm_loss_weight: 2.0
  freeze_text_branch: false
  # Feature Extraction
  audio:
    pool_type: avg
    feature_extractor_type: musicnn
    pretrained_version: null
    feature_extractor_path: ${env.data_root}/models/${model_config.audio.pretrained_version}/${model_config.audio.feature_extractor_type}.pth
    finetune: false
  bert:
    fusion_method: mul
    with_coattention: true
    t_biattention_id: [4,  5] 
    a_biattention_id: [0,  1] 
    bi_hidden_size: 1024 
    bi_num_attention_heads: 8
    bi_intermediate_size: 1024 
    bi_attention_type: 1 
    pooling_method: mul
    visualisation: false
    initializer_range: 0.02
    # pre-training
    multimodal_objective: atm   
    audio_objective: regression_mse
    text:
      attention_probs_dropout_prob: 0.1
      hidden_act: gelu
      hidden_dropout_prob: 0.1
      hidden_size: 768 
      intermediate_size: 3072 
      num_attention_heads: 12 
      num_hidden_layers: 6 
      # text only
      vocab_size: 30522   
      max_position_embeddings: 512  
      type_vocab_size: 2 
    audio:
      attention_probs_dropout_prob: 0.1 
      hidden_act: gelu 
      hidden_dropout_prob: 0.1  
      hidden_size: 256 
      intermediate_size: 1024 
      num_attention_heads: 8 
      num_hidden_layers: 6
      max_audio_length: 20 # in seconds
      # audio only
      feature_size: 1506 
      target_size: 1506

